### ISSUE TITLE
BAM files in config should go in files block

### ISSUE THREAD

**Issue by jblachly** [blachlylab/mucor#1]
bam object should be another element in files array with type BAM ; mucor should ignore all type BAM

{
      "bam": [
        {
          "path": "project/dir1/sample1.bam"
        }
      ],
      "files": [
        {
          "path": "project/dir1/sample1-a.vcf",
          "snpeff": false,
          "source": "VarScan",
          "type": "vcf"
        },

**Comment by kwkroll32** [comment]
bam files and vcf files live harmoniously under the respective sample block.
